jenkins:
  securityRealm:
    local: # Local user database
      allowsSignup: false
      users:
        - id: "admin"
          password: "${ADMIN_PASSWORD:-changeme}"
        - id: "developer"
          password: "${DEVELOPER_PASS:-changeme}"
  authorizationStrategy:
    globalMatrix:
      permissions:
        # keep an admin!
        - "Overall/Administer:admin"

        # let all signed-in users see the UI
        - "Overall/Read:authenticated"
        - "View/Read:authenticated"

        # grant Developer some specific powers
        - "Job/Build:developer"
        - "Job/Read:developer"